export const AuditEventTypes = {
  CART_ITEM_ADDED: "CART_ITEM_ADDED",
  CART_ITEM_REMOVED: "CART_ITEM_REMOVED",
  PRODUCT_VIEWED: "PRODUCT_VIEWED",
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  TICKET_CREATED: "TICKET_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED"
};

export const getAuditEventsList = () => Object.values(AuditEventTypes);
