name = "bodilicious-seo"
main = "worker.js"
compatibility_date = "2024-09-23"


[vars]
SEO_BOT_RENDER_ENABLED = "true"
API_BASE_URL = "https://bodilicious-cxow.onrender.com"
FRONTEND_URL = "https://bodilicious.in"
